In [1]:
import tensorflow as tf

In [2]:
# create a constant tensor A
A=tf.constant([[4,6],
               [6,1]])

In [5]:
# create a constant tensor B
B=tf.constant([[7,8],
               [4,5]])

In [6]:
# create a Variable tensor V
V=tf.Variable([[3,1],
               [5,2]])


In [9]:

B


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5]])>

In [11]:
# Concatinate columns
AB_concatinated= tf.concat(values=[A,B], axis=1)

In [12]:
AB_concatinated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 6, 7, 8],
       [6, 1, 4, 5]])>

In [13]:
AB_concatinated= tf.concat(values=[A,B], axis=0)

In [14]:
AB_concatinated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 6],
       [6, 1],
       [7, 8],
       [4, 5]])>